version: "3"

networks:
  loki:


services:
  fluentbit:
    image: fluent/fluent-bit:2.1.2
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    ports:
      - 2021:2021
      - "24224:24224"
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/logs

  nginx:
    image: nginx:latest
    ports:
      - "18080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    restart: always
    # one:
    #   ports:
    #     - "8080:8080"
    #   build:
    #     context: ./one
    # volumes:
    #   - ./logs:/logs
  loki:
    image: grafana/loki:2.8.0
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      DOCKER_HOST: /var/run/docker.sock
    # networks:
    #   - loki
    # promtail:
    #   image: grafana/promtail:2.8.0
    #   volumes:
    #     - /var/log:/var/log #- /Users/qunlinwu/.colima/default/docker.sock:/var/run/docker.sock
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - ./promtail-config.yml:/etc/promtail/config.yml
    #   command: -config.file=/etc/promtail/config.yml
    #   environment:
    #     DOCKER_HOST: /Users/qunlinwu/.colima/default/docker.sock
    #   networks:
    #     - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
