version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    volumes:
      - shared-volume:/usr/app/
      - ./kafka.yml:/usr/app/prom-jmx-agent-config.yml

  jmx-agent:
    build:
      dockerfile: Dockerfile.agent
      context: .
    entrypoint: [ "/bin/sh", "-c", "tail", "-f", "/dev/null" ]
    volumes:
      - shared-volume:/opt

volumes:
  shared-volume:
