apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  volumes:
  - name: shared
    emptyDir: {}

  containers:
  - image: nginx
    name: main-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared
      mountPath: /var/opt

  - name: sidecar-container
    image: busybox
    args:
     - /bin/sh
     - -c
     - mkdir -p /var/opt && echo 'sidecar-demo' > /var/opt/share.log && tail -f /dev/null
    volumeMounts:
    - name: shared
      mountPath: /var/opt